feature/#46-Create-Doughnut-chart-for-showing-the-services-called-on-the-Dashboard-Frontend
ChristophBaierATB/coatrack pull request #3
Opened 2020-11-02 11:06 UTC by ChristophBaierATB

2020-11-02 11:07 UTC, ChristophBaierATB reviewed
Values to change.

2020-11-02 11:07 UTC, ChristophBaierATB commented on spring-boot/admin/src/main/resources/messages.properties
> +admin.dashboard.stats.calls.per.service.desc=Shows the number of calls per service in the selected data-range
Please Christoph, change this value to

2020-11-02 12:49 UTC, BrunoSilvaATB requested changes
Christoph, please proceed to apply these changes so that I can start the merging process with the backend.

2020-11-02 12:49 UTC, BrunoSilvaATB commented on spring-boot/admin/src/main/resources/templates/admin/dashboard.html
> +                    loadChart('/admin/dashboard/userStatsDoughnutChart' + dateRangeUrlSuffix, 'callsPerServiceChartCanvas');
@ChristophBaierATB please change this to `loadChart('/admin/dashboard/serviceStatsChartCanvas ' + dateRangeUrlSuffix, 'callsPerServiceChartCanvas');`

2020-11-03 07:42 UTC, BrunoSilvaATB approved these changes
The code is now approved and will be merged to the Backend code.

2020-11-03 07:43 UTC, closed without merging